name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/brianlii/latex-build:latest
      credentials:
         username: ${{  secrets.DOCKER_USERNAME }}
         password: ${{  secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: build and push
        shell: bash
        run: |
          bash /build.sh ${{  secrets._GITHUB_HJ84_PAT }}
